/* 
This file is auto generated by pgx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- src/lib.rs:40
-- postmask::remove_user_from_group
CREATE  FUNCTION "remove_user_from_group"(
	"user" TEXT, /* &str */
	"group" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'remove_user_from_group_wrapper';

-- src/lib.rs:58
-- postmask::remove_user_from_all_group
CREATE  FUNCTION "remove_user_from_all_group"(
	"user" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'remove_user_from_all_group_wrapper';

-- src/lib.rs:92
-- postmask::remove_object_from_group
CREATE  FUNCTION "remove_object_from_group"(
	"group" TEXT, /* &str */
	"object" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'remove_object_from_group_wrapper';

-- src/faking.rs:43
-- postmask::faking::random_provide
CREATE  FUNCTION "random_provide"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'random_provide_wrapper';

-- src/faking.rs:33
-- postmask::faking::random_name
CREATE  FUNCTION "random_name"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'random_name_wrapper';

-- src/lib.rs:110
-- postmask::partial_mask_str
CREATE  FUNCTION "partial_mask_str"(
	"object" TEXT, /* &str */
	"value" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'partial_mask_str_wrapper';

-- src/randomization.rs:8
-- postmask::randomization::mask_with_random_str
CREATE  FUNCTION "mask_with_random_str"(
	"object" TEXT, /* &str */
	"value" TEXT, /* &str */
	"n" INT /* i32 */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mask_with_random_str_wrapper';

-- src/randomization.rs:52
-- postmask::randomization::mask_with_random_phone
CREATE  FUNCTION "mask_with_random_phone"(
	"object" TEXT, /* &str */
	"value" TEXT, /* &str */
	"prefix" TEXT, /* &str */
	"n" INT /* i32 */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mask_with_random_phone_wrapper';

-- src/randomization.rs:33
-- postmask::randomization::mask_with_random_integer_between
CREATE  FUNCTION "mask_with_random_integer_between"(
	"object" TEXT, /* &str */
	"value" INT, /* i32 */
	"min" INT, /* i32 */
	"max" INT /* i32 */
) RETURNS INT /* core::result::Result<i32, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mask_with_random_integer_between_wrapper';

-- src/randomization.rs:23
-- postmask::randomization::mask_with_random_integer
CREATE  FUNCTION "mask_with_random_integer"(
	"object" TEXT, /* &str */
	"value" INT /* i32 */
) RETURNS INT /* core::result::Result<i32, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mask_with_random_integer_wrapper';

-- src/faking.rs:23
-- postmask::faking::mask_str_with_fake_provinde
CREATE  FUNCTION "mask_str_with_fake_provinde"(
	"object" TEXT, /* &str */
	"value" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mask_str_with_fake_provinde_wrapper';

-- src/faking.rs:13
-- postmask::faking::mask_str_with_fake_name
CREATE  FUNCTION "mask_str_with_fake_name"(
	"object" TEXT, /* &str */
	"value" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mask_str_with_fake_name_wrapper';

-- src/destruction.rs:12
-- postmask::destruction::mask_str_replace
CREATE  FUNCTION "mask_str_replace"(
	"object" TEXT, /* &str */
	"value" TEXT, /* &str */
	"replaced_with" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mask_str_replace_wrapper';

-- src/destruction.rs:6
-- postmask::destruction::mask_str
CREATE  FUNCTION "mask_str"(
	"object" TEXT, /* &str */
	"value" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mask_str_wrapper';

-- src/adding_noise.rs:7
-- postmask::adding_noise::mask_integer_with_noise
CREATE  FUNCTION "mask_integer_with_noise"(
	"object" TEXT, /* &str */
	"value" INT, /* i32 */
	"ratio" real /* f32 */
) RETURNS INT /* core::result::Result<i32, pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mask_integer_with_noise_wrapper';

-- src/lib.rs:138
-- postmask::hello_postmask
CREATE  FUNCTION "hello_postmask"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'hello_postmask_wrapper';

-- src/lib.rs:24
-- postmask::assign_user_to_group
CREATE  FUNCTION "assign_user_to_group"(
	"user" TEXT, /* &str */
	"group" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'assign_user_to_group_wrapper';

-- src/lib.rs:75
-- postmask::assign_object_to_group
CREATE  FUNCTION "assign_object_to_group"(
	"object" TEXT, /* &str */
	"group" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgx::spi::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'assign_object_to_group_wrapper';

-- src/lib.rs:8

create table unmask_user (
    unmask_user text not null,
    unmask_group text not null
);
create table unmask_object (
    unmask_object text not null,
    unmask_group text not null
);

